# Generated by Django 5.1.1 on 2024-09-17 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiStadium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('nickName', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('battingHand', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('bowling', models.CharField(blank=True, max_length=20, null=True)),
                ('batting', models.CharField(blank=True, max_length=20, null=True)),
                ('fielding', models.CharField(blank=True, max_length=20, null=True)),
                ('wicketKeeping', models.CharField(blank=True, max_length=20, null=True)),
                ('heightType', models.CharField(blank=True, max_length=50, null=True)),
                ('bowlingType', models.CharField(blank=True, max_length=50, null=True)),
                ('battingType', models.CharField(blank=True, max_length=50, null=True)),
                ('batterType', models.CharField(blank=True, max_length=50, null=True)),
                ('bowlerType', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiStadium.nationality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
