# Generated by Django 5.1.1 on 2024-09-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bowlingHand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
