# Generated by Django 5.1.1 on 2024-09-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiPlayer', '0002_player_bowlinghand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='batterType',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bowlerType',
        ),
    ]
