# Generated by Django 5.1.1 on 2024-09-18 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiStadium', '0001_initial'),
        ('apiTeam', '0001_initial'),
        ('apiTournament', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('innings', models.IntegerField(default=2)),
                ('isLimitedOvers', models.BooleanField(default=True)),
                ('activePlayersPerTeam', models.IntegerField(default=11)),
                ('oversPerInnings', models.IntegerField()),
                ('ballsPerOver', models.IntegerField()),
                ('widePenaltyRuns', models.IntegerField()),
                ('noBallPenaltyRuns', models.IntegerField()),
                ('hasFreeHit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('displayName', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=20)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('matchCount', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('hostingNation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiStadium.nationality')),
                ('teams', models.ManyToManyField(blank=True, null=True, to='apiTeam.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTournament.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matchType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCompetition.matchtype')),
            ],
        ),
    ]
