# Generated by Django 5.1.1 on 2024-09-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCompetition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='hasUpdatedSquad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='hasUpdatedTeams',
            field=models.BooleanField(default=False),
        ),
    ]
