# Generated by Django 5.1.1 on 2024-09-20 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCompetition', '0002_competition_hasupdatedsquad_and_more'),
        ('apiPlayer', '0003_remove_player_battertype_remove_player_bowlertype'),
        ('apiTeam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionTeamSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCompetition.competition')),
                ('players', models.ManyToManyField(to='apiPlayer.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTeam.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
