# Generated by Django 5.1.1 on 2024-09-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCompetition', '0004_knockout'),
        ('apiTeam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(to='apiTeam.team'),
        ),
    ]
