# Generated by Django 5.1.1 on 2024-09-25 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiMatch', '0003_match_playingsquadcount'),
        ('apiPlayer', '0003_remove_player_battertype_remove_player_bowlertype'),
        ('apiTeam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField()),
                ('battingTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battingTeam', to='apiTeam.team')),
                ('bowlingTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowlingTeam', to='apiTeam.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiMatch.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballOver', models.FloatField()),
                ('strikerRuns', models.IntegerField(default=0)),
                ('bowlerRuns', models.IntegerField(default=0)),
                ('extraRuns', models.IntegerField(default=0)),
                ('teamRuns', models.IntegerField(default=0)),
                ('wideRuns', models.IntegerField(default=0)),
                ('noBallRuns', models.IntegerField(default=0)),
                ('penaltyRuns', models.IntegerField(default=0)),
                ('legByeRuns', models.IntegerField(default=0)),
                ('byeRuns', models.IntegerField(default=0)),
                ('noBallType', models.CharField(blank=True, max_length=30, null=True)),
                ('overThrowRuns', models.IntegerField(default=0)),
                ('wicketType', models.CharField(blank=True, max_length=30, null=True)),
                ('editLater', models.BooleanField(default=False)),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler', to='apiPlayer.player')),
                ('dismissalAssistBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismissalAssistBy', to='apiPlayer.player')),
                ('dismissedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismissalBy', to='apiPlayer.player')),
                ('fielder1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fielder1', to='apiPlayer.player')),
                ('fielder2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fielder2', to='apiPlayer.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiMatch.match')),
                ('nonStriker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_striker', to='apiPlayer.player')),
                ('striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='striker', to='apiPlayer.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiBall.innings')),
            ],
        ),
    ]
