# Generated by Django 5.1.1 on 2024-09-26 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBall', '0001_initial'),
        ('apiTeam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innings',
            name='battingTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battingTeamA', to='apiTeam.team'),
        ),
        migrations.AlterField(
            model_name='innings',
            name='bowlingTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowlingTeamB', to='apiTeam.team'),
        ),
    ]
