# Generated by Django 5.1.1 on 2024-09-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBall', '0002_alter_innings_battingteam_alter_innings_bowlingteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='batSubject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='batsmanActivity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='creaseMovement',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='deliveryType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='fieldingActivity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='keeperActivity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='shotConnection',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='stroke',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='umpireActivity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
