# Generated by Django 5.1.1 on 2024-09-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBall', '0003_ball_batsubject_ball_batsmanactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='ballTrajectoryX',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='ballTrajectoryY',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='bowlerReleasePosition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='bowlerReleaseX',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='bowlerReleaseY',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='shotZoneX',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='shotZoneY',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='wagonWheelX',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='wagonWheelY',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ball',
            name='wicketKeeperPosition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
