# Generated by Django 5.1.1 on 2024-09-29 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBall', '0004_ball_balltrajectoryx_ball_balltrajectoryy_and_more'),
        ('apiPlayer', '0003_remove_player_battertype_remove_player_bowlertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='dismissedPlayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismissedPlayer', to='apiPlayer.player'),
        ),
    ]
