# Generated by Django 5.1.1 on 2024-09-30 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBall', '0005_ball_dismissedplayer'),
        ('apiPlayer', '0003_remove_player_battertype_remove_player_bowlertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ball',
            name='dismissalAssistBy',
        ),
        migrations.AddField(
            model_name='ball',
            name='caughtBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caughtBy', to='apiPlayer.player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='runOutFielder1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runOutFielder1', to='apiPlayer.player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='runOutFielder2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runOutFielder2', to='apiPlayer.player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='stumpedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stumpedBy', to='apiPlayer.player'),
        ),
    ]
