# Generated by Django 5.1.1 on 2024-09-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBall', '0006_remove_ball_dismissalassistby_ball_caughtby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='isShortRuns',
            field=models.BooleanField(default=False),
        ),
    ]
