# Generated by Django 5.1.1 on 2024-09-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBall', '0007_ball_isshortruns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='innings',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Innings',
        ),
    ]
