# Generated by Django 5.1.1 on 2024-10-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBall', '0008_alter_ball_innings_delete_innings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='isBoundary',
            field=models.BooleanField(default=False),
        ),
    ]
