# Generated by Django 5.1.1 on 2024-10-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSubscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='razorPayPlanId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
