# Generated by Django 5.1.1 on 2024-10-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSubscription', '0002_usersubscription_razorpayplanid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='razorPayPlanId',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
