# Generated by Django 5.1.1 on 2024-10-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSubscription', '0003_subscriptionplan_razorpayplanid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='url',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
