# Generated by Django 5.1.1 on 2024-10-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSubscription', '0004_subscriptionplan_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='durationCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiSubscription.subscriptionduration'),
            preserve_default=False,
        ),
    ]
