# Generated by Django 5.1.1 on 2024-10-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSubscription', '0005_subscriptionplan_durationcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='isValid',
            field=models.BooleanField(default=False),
        ),
    ]
