# Generated by Django 5.1.1 on 2024-10-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSubscription', '0006_usersubscription_isvalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='displayName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
