# Generated by Django 5.1.1 on 2024-09-22 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiCompetition', '0004_knockout'),
        ('apiPlayer', '0003_remove_player_battertype_remove_player_bowlertype'),
        ('apiStadium', '0001_initial'),
        ('apiTeam', '0001_initial'),
        ('apiUmpire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('matchCondition', models.CharField(blank=True, max_length=30, null=True)),
                ('knockOut', models.CharField(blank=True, max_length=30, null=True)),
                ('optTo', models.CharField(blank=True, max_length=20, null=True)),
                ('isVideoCaptureEnabled', models.CharField(max_length=3)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCompetition.competition')),
                ('firstUmpire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='umpire1', to='apiUmpire.umpire')),
                ('matchType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCompetition.matchtype')),
                ('secondUmpire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='umpire2', to='apiUmpire.umpire')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiStadium.stadium')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='apiTeam.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='apiTeam.team')),
                ('thirdUmpire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='umpire3', to='apiUmpire.umpire')),
                ('tossWonBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiTeam.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayingSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCompetition.competition')),
                ('players', models.ManyToManyField(to='apiPlayer.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTeam.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
