# Generated by Django 5.1.1 on 2024-09-23 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMatch', '0001_initial'),
        ('apiPlayer', '0003_remove_player_battertype_remove_player_bowlertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playingsquad',
            name='competition',
        ),
        migrations.AddField(
            model_name='playingsquad',
            name='captain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='apiPlayer.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playingsquad',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiMatch.match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playingsquad',
            name='wicketKeeper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wicketkeper', to='apiPlayer.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playingsquad',
            name='players',
            field=models.ManyToManyField(related_name='players', to='apiPlayer.player'),
        ),
    ]
