# Generated by Django 5.1.1 on 2024-09-26 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMatch', '0003_match_playingsquadcount'),
        ('apiTeam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='firstInningsBattingTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='firstInningsBattingTeam', to='apiTeam.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='firstInningsBowlingTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='firstInningsBowlingTeam', to='apiTeam.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='fourthInningsBattingTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fourthInningsBattingTeam', to='apiTeam.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='fourthInningsBowlingTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fourthInningsBowlingTeam', to='apiTeam.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='secondInningsBattingTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secondInningsBattingTeam', to='apiTeam.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='secondInningsBowlingTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secondInningsBowlingTeam', to='apiTeam.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='thirdInningsBattingTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thirdInningsBattingTeam', to='apiTeam.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='thirdInningsBowlingTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thirdInningsBowlingTeam', to='apiTeam.team'),
            preserve_default=False,
        ),
    ]
