# Generated by Django 5.1.1 on 2024-09-26 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMatch', '0004_match_firstinningsbattingteam_and_more'),
        ('apiTeam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='firstInningsBattingTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstInningsBattingTeam', to='apiTeam.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='firstInningsBowlingTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstInningsBowlingTeam', to='apiTeam.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='fourthInningsBattingTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourthInningsBattingTeam', to='apiTeam.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='fourthInningsBowlingTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourthInningsBowlingTeam', to='apiTeam.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='secondInningsBattingTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondInningsBattingTeam', to='apiTeam.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='secondInningsBowlingTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondInningsBowlingTeam', to='apiTeam.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='thirdInningsBattingTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdInningsBattingTeam', to='apiTeam.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='thirdInningsBowlingTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdInningsBowlingTeam', to='apiTeam.team'),
        ),
    ]
