# Generated by Django 5.1.1 on 2024-09-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMatch', '0005_alter_match_firstinningsbattingteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='currentInnings',
            field=models.IntegerField(default=1),
        ),
    ]
