# Generated by Django 5.1.1 on 2024-10-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMatch', '0007_match_matchended_match_matchresult'),
        ('apiTeam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='currentLeadingTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leading_team', to='apiTeam.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='currentSuperOverCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='currentTarget',
            field=models.IntegerField(default=0),
        ),
    ]
