# Generated by Django 5.1.1 on 2024-11-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMatch', '0009_match_leadingteamchoseto'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='hasMatchVideosUploadCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
