# Generated by Django 5.1.1 on 2024-09-17 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiStadium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Umpire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiStadium.nationality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umpires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
